### ISSUE TITLE
the chatbot didn't respond

### ISSUE THREAD

**Issue by SallemiDorsaf** [Alexmhack/Django-Rasa-Sockets#3]
thank you for the code it's very helpful
but my bot didn't respond
rasa =1.1.4

> from rasa.core.agent import Agent
from rasa.core.channels.socketio import SocketIOInput
from rasa.core.agent import Agent
from rasa.utils.endpoints import EndpointConfig
interpreter ="models/20190809-043054/nlu"
MODEL_PATH = "models/20190809-043054/core"
action_endpoint = EndpointConfig(url="http://127.0.0.1:5055/webhook")
agent = Agent.load(MODEL_PATH, interpreter=interpreter,
                   action_endpoint=action_endpoint)
input_channel = SocketIOInput(
	user_message_evt="user_uttered",
	bot_message_evt="bot_uttered",
	namespace=None
)
s = agent.handle_channels([input_channel], http_port=5500,route='/webhooks/',cors="*")
> 
i run : rasa run actions  // python bot.py // python manage.py runserver
i can tape a message but i didn't get a response can you help me to fix it thank you

**Comment by Alexmhack** [comment]
Have you checked the browser console, look for any errors there, maybe socket could not connect to rasa server.

**Comment by SallemiDorsaf** [comment]
i get this 
![image](https://user-images.githubusercontent.com/50247999/63003306-5a5e8980-bed4-11e9-8092-3957e44d60cf.png)
can you help me to fix it please

**Comment by Alexmhack** [comment]
I have updated the code for django backend to allow CORS (the issue you are facing), it should work fine now, I couldn't test it due to some problems with my local machine, see if it worked for you.

run `git pull` to update your repo and test by running both the servers again.

**Comment by SallemiDorsaf** [comment]
it didn't work  i get this error
![image](https://user-images.githubusercontent.com/50247999/63082849-c8be4d00-bfa3-11e9-8973-e9611bf59549.png)

**Comment by Alexmhack** [comment]
Sorry for the late response but I am not getting any good workaround solution for this problem after a lot of testing, I think you should try the same thing in the google chrome browser as well for checking if it works in that browser, you can also google search this problem, and make any changes on your side and do tell me if anything worked for you,

Looking forward to see a solution.

**Comment by Alexmhack** [comment]
I think there is some problem going on with Rasa related to how sockets work, checkout [here](https://github.com/RasaHQ/rasa/pull/4303)

**Comment by Alexmhack** [comment]
Hi @SallemiDorsa, For your issue, you should try installing the latest version of rasa from [here](https://rasa.com/docs/getting-started/) and in case of detailed instructions go [here](https://rasa.com/docs/rasa/user-guide/installation).

After installing, instead of using my repo for a chat interface, use [webchat](https://github.com/mrbot-ai/rasa-webchat), its safe, uses sockets and works fine, but the above installation is required.

In case of getting errors while installing `rasa-x` on windows due to `httptools build error` checkout [this](https://rasa.com/docs/rasa/user-guide/installation/#install-the-python-development-environment) and go to **Windows** tab below the line, **Otherwise, proceed with the instructions below to install them.** on the same page.

See if it works for you.
